spring:
  application:
    name: spring-eureka
  freemarker:
    template-loader-path: classpath:/templates
    prefer-file-system-access: false
  boot:
    admin:
      client:
        url: http://localhost:1880
        username: admin
        password: admin
        instance:
          metadata:
            usename: admin
            password: admin
        api-path: /instances

   
server:
  port: 8761
  
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    
    
zuul:
  prefix: /api
  routes:
    spring-producer:
          path: /spring-producer/**
          url: http://localhost:1990
    spring-consumer:
           path: /spring-consumer/**
           url: http://localhost:1991
           
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS  
