spring:
  application:
    name: spring-eureka
  freemarker:
    template-loader-path: classpath:/templates
    prefer-file-system-access: false

   
server:
  port: 8761
  
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    
    
zuul:
  prefix: /api
  routes:
    spring-producer:
          path: /spring-producer/**
          url: http://localhost:1990
    spring-consumer:
           path: /spring-consumer/**
           url: http://localhost:1991
